spring.application.name=hospitalduoc


server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalduoc
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect