spring.application.name=apigateway

server.port=9090
spring.cloud.gateway.server.webmvc.routes[0].id=servicio-pacientes
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/pacientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=servicio-medicos
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/medicos/** 

spring.cloud.gateway.server.webmvc.routes[2].id=servicio-atencion
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/atencion/** 
